# in memory database
spring:
  datasource:
    platform: h2
    url: jdbc:h2:mem:bankingdb
    driverClassName: org.h2.Driver
    username: admin 
    password:
  jpa:
    properties:
      hibernate:
        format_sql: true

# logging
logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE